USE GD1C2020

-- Tablas a testear --
/*
	GRUPO2.Aerolinea
	GRUPO2.Avion
	GRUPO2.Butaca
	GRUPO2.Ciudad
	GRUPO2.Ruta_Aerea
*/

-- Elimino los objetos creados anteriormente para evitar el error de que ya existen --




-- Aca va funcionalidad útil --


-- Aca van los triggers --


-- Aca van los procedures --
GO
	CREATE PROCEDURE MIGRAR_AEROLINEAS
	AS
	BEGIN
		INSERT INTO GRUPO2.Aerolinea
			SELECT DISTINCT EMPRESA_RAZON_SOCIAL FROM gd_esquema.Maestra WHERE dbo.ES_UNA_AEROLINEA(EMPRESA_RAZON_SOCIAL) = 1
	END
GO

GO
	CREATE PROCEDURE MIGRAR_AVIONES
	AS
	BEGIN
		INSERT INTO GRUPO2.Avion(avion_identificador, avion_aerolinea, avion_modelo)
			SELECT AVION_IDENTIFICADOR, EMPRESA_RAZON_SOCIAL, AVION_MODELO FROM gd_esquema.Maestra WHERE dbo.ES_UNA_AEROLINEA(EMPRESA_RAZON_SOCIAL) = 1 GROUP BY AVION_MODELO, AVION_IDENTIFICADOR, EMPRESA_RAZON_SOCIAL
	END
GO

GO
	CREATE PROCEDURE MIGRAR_BUTACAS
	AS
	BEGIN
		INSERT INTO GRUPO2.Butaca(butaca_numero, butaca_avion, butaca_aerolinea, butaca_tipo)
			SELECT BUTACA_NUMERO, AVION_IDENTIFICADOR, EMPRESA_RAZON_SOCIAL, BUTACA_TIPO FROM gd_esquema.Maestra WHERE AVION_IDENTIFICADOR IS NOT NULL GROUP BY BUTACA_NUMERO, AVION_IDENTIFICADOR, EMPRESA_RAZON_SOCIAL, BUTACA_TIPO
	END
GO

GO
	CREATE PROCEDURE MIGRAR_CIUDADES
	AS
	BEGIN
		INSERT INTO GRUPO2.Ciudad(ciudad_nombre)
			(
				(SELECT DISTINCT RUTA_AEREA_CIU_DEST FROM gd_esquema.Maestra WHERE RUTA_AEREA_CIU_DEST IS NOT NULL)
				UNION
				(SELECT DISTINCT RUTA_AEREA_CIU_ORIG FROM gd_esquema.Maestra WHERE RUTA_AEREA_CIU_ORIG IS NOT NULL)
			)
	END
GO

GO
	CREATE PROCEDURE MIGRAR_RUTAS_AEREAS
	AS
	BEGIN
		INSERT INTO GRUPO2.Ruta_Aerea(ruta_aerea_codigo, ruta_aerea_ciudad_origen, ruta_aerea_ciudad_destino)
			SELECT DISTINCT RUTA_AEREA_CODIGO, dbo.CODIGO_CIUDAD(RUTA_AEREA_CIU_ORIG), dbo.CODIGO_CIUDAD(RUTA_AEREA_CIU_DEST) FROM gd_esquema.Maestra WHERE RUTA_AEREA_CODIGO IS NOT NULL
	END
GO

-- Ejecución de los procedures --
--EXECUTE MIGRAR_AEROLINEAS
--EXECUTE MIGRAR_AVIONES
--EXECUTE MIGRAR_BUTACAS
--EXECUTE MIGRAR_CIUDADES
--EXECUTE MIGRAR_RUTAS_AEREAS

-- Verificación de las tablas --
SELECT * FROM GRUPO2.Aerolinea
SELECT * FROM GRUPO2.Avion
SELECT * FROM GRUPO2.Butaca
SELECT * FROM GRUPO2.Ciudad
SELECT * FROM GRUPO2.Ruta_Aerea