USE [GD1C2020]

-- Creación de Tablas --
CREATE TABLE empresa(
    RAZON_SOCIAL NVARCHAR(255) NOT NULL,
    NOMBRE NVARCHAR(255) NOT NULL,

    PRIMARY KEY(RAZON_SOCIAL)
);

CREATE TABLE tipo_usuario(
    ID NVARCHAR(50) NOT NULL,
    NOMBRE NVARCHAR(255) NOT NULL,

    PRIMARY KEY(ID)
);

CREATE TABLE operacion(
    NUMERO DECIMAL(18,0) NOT NULL,
    fecha DATETIME2(3) NOT NULL,
    DNI_cliente DECIMAL(18, 0) NOT NULL,
    tipo NVARCHAR(50) NOT NULL,

    PRIMARY KEY(NUMERO)
);

CREATE TABLE sucursal(
    MAIL NVARCHAR(255) NOT NULL,
    direccion NVARCHAR(255) NOT NULL,
    telefono DECIMAL(18, 0) NOT NULL
);

CREATE TABLE factura(
    NUMERO_OPERACION DECIMAL(18,0) NOT NULL,
    TIPO_OPERACION NVARCHAR(50) NOT NULL,
    fecha DATETIME2(3) NOT NULL,
    costo DECIMAL(18, 2) NOT NULL,

    PRIMARY KEY(NUMERO_OPERACION, TIPO_OPERACION),
    FOREIGN KEY(mail_sucursal) REFERENCES sucursal(MAIL) ON DELETE SET NULL
);

CREATE TABLE usuario(
    DNI DECIMAL(18,0) NOT NULL,
    nombre NVARCHAR(255) NOT NULL,
    apellido NVARCHAR(255) NOT NULL,
    mail NVARCHAR(255) NOT NULL,
    telefono DECIMAL(18,0) NOT NULL,

    PRIMARY KEY(DNI),
    FOREIGN KEY(EMPRESA) REFERENCES empresa(RAZON_SOCIAL),
    FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES tipo_usuario(ID)
);