USE GD1C2020

-- Tablas a testear --
/*
	GRUPO2.Empresa
	GRUPO2.Usuario
	GRUPO2.Sucursal
	GRUPO2.Factura
	GRUPO2.Operacion
*/

-- Elimino los objetos creados anteriormente para evitar el error de que ya existen --
IF EXISTS (SELECT name FROM sysobjects WHERE name='MIGRAR_EMPRESAS')
	DROP PROCEDURE MIGRAR_EMPRESAS
IF EXISTS (SELECT name FROM sysobjects WHERE name='MIGRAR_USUARIOS')
	DROP PROCEDURE MIGRAR_USUARIOS
IF EXISTS (SELECT name FROM sysobjects WHERE name='MIGRAR_SUCURSALES')
	DROP PROCEDURE MIGRAR_SUCURSALES
IF EXISTS (SELECT name FROM sysobjects WHERE name='MIGRAR_FACTURAS')
	DROP PROCEDURE MIGRAR_FACTURAS
IF EXISTS (SELECT name FROM sysobjects WHERE name='MIGRAR_OPERACIONES')
	DROP PROCEDURE MIGRAR_OPERACIONES
IF EXISTS (SELECT name FROM sysobjects WHERE name='COSTO_OPERACION_ESTADIA')
	DROP FUNCTION COSTO_OPERACION_ESTADIA


-- Aca van los procedures --
GO
	CREATE PROCEDURE MIGRAR_EMPRESAS
	AS
	BEGIN
		INSERT INTO GRUPO2.Empresa
			SELECT DISTINCT EMPRESA_RAZON_SOCIAL FROM gd_esquema.Maestra
	END
GO

GO
	CREATE PROCEDURE MIGRAR_USUARIOS
	AS
	BEGIN
		INSERT INTO GRUPO2.Usuario
			SELECT DISTINCT CLIENTE_DNI, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_MAIL, CLIENTE_TELEFONO FROM gd_esquema.Maestra 
			WHERE CLIENTE_DNI IS NOT NULL 
			AND CLIENTE_NOMBRE IS NOT NULL 
			AND CLIENTE_APELLIDO IS NOT NULL 
			AND CLIENTE_MAIL IS NOT NULL 
			AND CLIENTE_TELEFONO IS NOT NULL
	END
GO

GO
	CREATE PROCEDURE MIGRAR_SUCURSALES
	AS
	BEGIN
		INSERT INTO GRUPO2.Sucursal
			SELECT DISTINCT EMPRESA_RAZON_SOCIAL, SUCURSAL_MAIL, SUCURSAL_DIR, SUCURSAL_TELEFONO FROM gd_esquema.Maestra 
			WHERE EMPRESA_RAZON_SOCIAL IS NOT NULL 
			AND SUCURSAL_MAIL IS NOT NULL 
			AND SUCURSAL_DIR IS NOT NULL 
			AND SUCURSAL_TELEFONO IS NOT NULL 
	END
GO

GO
	CREATE FUNCTION COSTO_OPERACION_ESTADIA (@CODIGO_ESTADIA decimal(18, 0), @HOTEL varchar(255), @HOTEL_CALLE varchar(255), @HOTEL_NUMERO_CALLE varchar(255))
	RETURNS decimal(18, 2)
	AS
	BEGIN
		DECLARE @COSTO_FINAL decimal(18, 2)

		SELECT @COSTO_FINAL = SUM(habitacion_estadia_costo) 
		FROM GRUPO2.Habitacion_Estadia
		WHERE habitacion_estadia_codigo_estadia = @CODIGO_ESTADIA
		AND habitacion_estadia_hotel_nombre = @HOTEL
		AND habitacion_estadia_hotel_calle = @HOTEL_CALLE
		AND habitacion_estadia_hotel_numero_calle = @HOTEL_NUMERO_CALLE

		RETURN @COSTO_FINAL
	END
GO

GO
	CREATE PROCEDURE MIGRAR_FACTURAS
	AS
	BEGIN
		-- Primero inserto las operaciones de pasaje --
		INSERT INTO GRUPO2.Factura
			SELECT DISTINCT FACTURA_NRO, 'VENTA', SUCURSAL_DIR, EMPRESA_RAZON_SOCIAL, FACTURA_FECHA, (PASAJE_COSTO*1.2), CLIENTE_DNI, CLIENTE_NOMBRE, CLIENTE_APELLIDO FROM gd_esquema.Maestra 
			WHERE COMPRA_NUMERO IS NOT NULL 
			AND SUCURSAL_DIR IS NOT NULL 
			AND EMPRESA_RAZON_SOCIAL IS NOT NULL 
			AND FACTURA_FECHA IS NOT NULL
			AND PASAJE_COSTO IS NOT NULL
		-- Luego las operaciones de hotel --
		INSERT INTO GRUPO2.Factura
			SELECT DISTINCT FACTURA_NRO, 'VENTA', SUCURSAL_DIR, EMPRESA_RAZON_SOCIAL, FACTURA_FECHA, (dbo.COSTO_OPERACION_ESTADIA(ESTADIA_CODIGO, EMPRESA_RAZON_SOCIAL, HOTEL_CALLE, HOTEL_NRO_CALLE)*1.2), CLIENTE_DNI, CLIENTE_NOMBRE, CLIENTE_APELLIDO FROM gd_esquema.Maestra 
			WHERE COMPRA_NUMERO IS NOT NULL 
			AND SUCURSAL_DIR IS NOT NULL 
			AND EMPRESA_RAZON_SOCIAL IS NOT NULL 
			AND FACTURA_FECHA IS NOT NULL
			AND HABITACION_COSTO IS NOT NULL
	END
GO

GO
	CREATE PROCEDURE MIGRAR_OPERACIONES
	AS
	BEGIN
		INSERT INTO GRUPO2.Operacion
		SELECT COMPRA_NUMERO, (CASE WHEN FACTURA_NRO IS NOT NULL THEN 'VENTA' ELSE 'COMPRA' END), COMPRA_FECHA
		FROM gd_esquema.Maestra 
		WHERE (COMPRA_NUMERO IS NOT NULL) AND (COMPRA_FECHA IS NOT NULL)
		GROUP BY COMPRA_NUMERO, COMPRA_FECHA, (CASE WHEN FACTURA_NRO IS NOT NULL THEN 'VENTA' ELSE 'COMPRA' END)
	END
GO

-- Aca van los testeos de la tabla (ejecución de los procedures para ver que funcione bien) --
EXECUTE MIGRAR_EMPRESAS
EXECUTE MIGRAR_USUARIOS
EXECUTE MIGRAR_SUCURSALES
EXECUTE MIGRAR_OPERACIONES
EXECUTE MIGRAR_FACTURAS

--SELECT * FROM gd_esquema.Maestra
SELECT * FROM GRUPO2.Empresa